enum PieceType{

    PAWN = 1,
    KNIGHT = 2,
    BISHOP = 3,
    ROOK = 4,
    QUEEN = 5,
    KING = 6,
	WAR_MACHINE = 7,
	MINISTER = 8,
	GENERAL = 9,
	GIRAFFE_RIDER = 10,
	PICKET = 11,
	ELEPHANT_RIDER = 12,
	CAMEL_RIDER = 13,
	HERO = 14,
	CANNON = 15,
	CHECKER = 16,
	KING_CHECKER = 17,
	BATTLESHIP = 18,
	NIGHTRIDER = 19,
	ROSE_KNIGHT = 20
}
