type %~dp0\common\State.ts > out.ts 
type %~dp0\common\StaticColors.ts >> out.ts 
type %~dp0\common\Algorithms.ts >> out.ts 
type %~dp0\common\CallbackPool.ts >> out.ts 
type %~dp0\common\IDSequence.ts >> out.ts 
type %~dp0\view\HTMLObject.ts >> out.ts 
type %~dp0\view\HTMLBuilder.ts >> out.ts 
type %~dp0\view\ChoiceModal.ts >> out.ts 
type %~dp0\common\Color.ts  >> out.ts 
type %~dp0\common\SquareType.ts  >> out.ts 
type %~dp0\common\PieceType.ts  >> out.ts 
type %~dp0\common\PieceLocation.ts  >> out.ts 
type %~dp0\view\PieceImageDatabase.ts  >> out.ts 
type %~dp0\view\Piece.ts  >> out.ts 
type %~dp0\view\Square.ts  >> out.ts 
type %~dp0\view\Row.ts  >> out.ts 
type %~dp0\view\Board.ts  >> out.ts 
type %~dp0\view\Throbber.ts  >> out.ts 
type %~dp0\view\AlertText.ts  >> out.ts 
type %~dp0\model\Pos.ts  >> out.ts 
type %~dp0\model\MoveType.ts  >> out.ts 
type %~dp0\model\Move.ts  >> out.ts 
type %~dp0\model\MoveCollection.ts  >> out.ts 
type %~dp0\model\MoveFactory.ts  >> out.ts 
type %~dp0\model\PieceModel.ts  >> out.ts 
type %~dp0\model\pieces\RookModel.ts  >> out.ts 
type %~dp0\model\pieces\PawnModel.ts  >> out.ts 
type %~dp0\model\pieces\GiraffeRiderModel.ts  >> out.ts 
type %~dp0\model\pieces\KnightModel.ts  >> out.ts 
type %~dp0\model\pieces\BishopModel.ts  >> out.ts 
type %~dp0\model\pieces\KingModel.ts  >> out.ts 
type %~dp0\model\pieces\QueenModel.ts  >> out.ts 
type %~dp0\model\pieces\GeneralModel.ts  >> out.ts 
type %~dp0\model\pieces\MinisterModel.ts  >> out.ts 
type %~dp0\model\pieces\WarMachineModel.ts  >> out.ts 
type %~dp0\model\pieces\PicketModel.ts  >> out.ts 
type %~dp0\model\pieces\ElephantRiderModel.ts  >> out.ts 
type %~dp0\model\pieces\CamelRiderModel.ts  >> out.ts 
type %~dp0\model\pieces\CannonModel.ts  >> out.ts 
type %~dp0\model\PieceFactory.ts  >> out.ts 
type %~dp0\model\BoardModel.ts  >> out.ts 
type %~dp0\model\BoardFactory.ts  >> out.ts 
type %~dp0\model\Player.ts  >> out.ts 
type %~dp0\model\MiniMaxPlayer.ts  >> out.ts
type %~dp0\view\GameHTMLContainer.ts  >> out.ts 
type %~dp0\model\ChessGame.ts  >> out.ts  
type %~dp0\view\Console\ConsoleEntry.ts  >> out.ts 
type %~dp0\view\Console\MyConsole.ts  >> out.ts 
type %~dp0\controller\ConsoleController.ts  >> out.ts 
type %~dp0\controller\GameController.ts  >> out.ts 
type %~dp0\global\Preloader.ts  >> out.ts 
type %~dp0\global\CSSClass.ts  >> out.ts 
type %~dp0\global\CSSManager.ts  >> out.ts 
type %~dp0\global\GameBox.ts  >> out.ts 
type %~dp0\board_builder\BoardBuilderHTMLContainer.ts  >> out.ts 
type %~dp0\board_builder\BoardBuilderController.ts  >> out.ts 
type %~dp0\board_builder\BoardBuilder.ts  >> out.ts 
type %~dp0\global\RunCommands.ts  >> out.ts 