type %~dp0\common\IDSequence.ts > out.txt 
type %~dp0\view\HTMLObject.ts >> out.txt 
type %~dp0\view\HTMLBuilder.ts >> out.txt 
type %~dp0\common\Color.ts  >> out.txt 
type %~dp0\common\PieceType.ts  >> out.txt 
type %~dp0\common\PieceLocation.ts  >> out.txt 
type %~dp0\view\Piece.ts  >> out.txt 
type %~dp0\view\Pawn.ts  >> out.txt 
type %~dp0\view\Bishop.ts  >> out.txt 
type %~dp0\view\King.ts  >> out.txt 
type %~dp0\view\Queen.ts  >> out.txt 
type %~dp0\view\Knight.ts  >> out.txt 
type %~dp0\view\Rook.ts  >> out.txt 
type %~dp0\view\Square.ts  >> out.txt 
type %~dp0\view\Row.ts  >> out.txt 
type %~dp0\view\Board.ts  >> out.txt 
type %~dp0\model\Pos.ts  >> out.txt 
type %~dp0\model\Move.ts  >> out.txt 
type %~dp0\model\MoveCollection.ts  >> out.txt 
type %~dp0\model\MoveFactory.ts  >> out.txt 
type %~dp0\model\PieceModel.ts  >> out.txt 
type %~dp0\model\PieceFactory.ts  >> out.txt 
type %~dp0\model\BoardModel.ts  >> out.txt 
type %~dp0\controller\TestController.ts  >> out.txt 