type %~dp0\common\State.ts > out.txt 
type %~dp0\common\StaticColors.ts >> out.txt 
type %~dp0\common\Algorithms.ts >> out.txt 
type %~dp0\common\CallbackPool.ts >> out.txt 
type %~dp0\common\IDSequence.ts >> out.txt 
type %~dp0\view\HTMLObject.ts >> out.txt 
type %~dp0\view\HTMLBuilder.ts >> out.txt 
type %~dp0\common\Color.ts  >> out.txt 
type %~dp0\common\SquareType.ts  >> out.txt 
type %~dp0\common\PieceType.ts  >> out.txt 
type %~dp0\common\PieceLocation.ts  >> out.txt 
type %~dp0\view\PieceImageDatabase.ts  >> out.txt 
type %~dp0\view\Piece.ts  >> out.txt 
type %~dp0\view\Square.ts  >> out.txt 
type %~dp0\view\Row.ts  >> out.txt 
type %~dp0\view\Board.ts  >> out.txt 
type %~dp0\model\Pos.ts  >> out.txt 
type %~dp0\model\Move.ts  >> out.txt 
type %~dp0\model\MoveCollection.ts  >> out.txt 
type %~dp0\model\MoveFactory.ts  >> out.txt 
type %~dp0\model\PieceModel.ts  >> out.txt 
type %~dp0\model\pieces\RookModel.ts  >> out.txt 
type %~dp0\model\pieces\PawnModel.ts  >> out.txt 
type %~dp0\model\pieces\GiraffeRiderModel.ts  >> out.txt 
type %~dp0\model\pieces\KnightModel.ts  >> out.txt 
type %~dp0\model\pieces\BishopModel.ts  >> out.txt 
type %~dp0\model\pieces\KingModel.ts  >> out.txt 
type %~dp0\model\pieces\QueenModel.ts  >> out.txt 
type %~dp0\model\pieces\GeneralModel.ts  >> out.txt 
type %~dp0\model\pieces\MinisterModel.ts  >> out.txt 
type %~dp0\model\PieceFactory.ts  >> out.txt 
type %~dp0\model\BoardModel.ts  >> out.txt 
type %~dp0\model\BoardFactory.ts  >> out.txt 
type %~dp0\model\Player.ts  >> out.txt 
type %~dp0\model\MiniMaxPlayer.ts  >> out.txt 
type %~dp0\model\ChessGame.ts  >> out.txt  
type %~dp0\view\Console\ConsoleEntry.ts  >> out.txt 
type %~dp0\view\Console\MyConsole.ts  >> out.txt 
type %~dp0\controller\ConsoleController.ts  >> out.txt 
type %~dp0\controller\GameController.ts  >> out.txt 
type %~dp0\global\Preloader.ts  >> out.txt 
type %~dp0\global\CSSClass.ts  >> out.txt 
type %~dp0\global\CSSManager.ts  >> out.txt 